### PR TITLE
[WIP] add undo/redo functionality

### PR DESCRIPTION
**Pull request by mathisonian**
I'm opening this PR for discussion, as it isn't yet feature complete. It has the basic infrastructure that I think would be required for the feature, but needs to be hooked up to the UI still. 

I'm hoping to have a discussion about the best way to surface this in the UI.

### CODE REVIEW

**Comment by tanalan** [comment]
It'd be nice to have the usual command/control  (shift) Z keyboard shortcuts for em.

As for UI appearance ... perhaps as icons at the top viewport that have low opacity, and higher opacity on hover?

**Comment by megan-vo** [comment]
Agreed on the command/control Z for undo/redo in general (components and text in general). Will the undo/redo for components be scoped by their component (i.e. say someone edits a Header component and a button component but just wants to redo edits for their Header component) or will there just be one general, app-wide undo/redo stack for everything (text and insertion of components included)?

I was thinking if component scoped, maybe have small undo/redo arrow buttons below the Properties/Code buttons that maybe appear on hover similar to Alan?

**Comment by tanalan** [comment]
Having individual undo/redo for each component seem difficult to implement with different component actions overlap with each other 🤔

**Comment by megan-vo** [comment]
Ah that's true. Thinking..

**Comment by megan-vo** [comment]
> It'd be nice to have the usual command/control (shift) Z keyboard shortcuts for em.
> 
> As for UI appearance ... perhaps as icons at the top viewport that have low opacity, and higher opacity on hover?

Top right perhaps? Since that's not taken up by anything o.o

**Comment by megan-vo** [comment]
Another question I have is will the render view naturally scroll to the place that is undone/redone? I think that might be nice but not sure if that's too much jumping around

**Comment by mathisonian** [comment]
> It'd be nice to have the usual command/control (shift) Z keyboard shortcuts for em.

+1 for keyboard shortcuts, that's a good idea. 

> Top right perhaps? Since that's not taken up by anything o.o

That seems reasonable. I was going to suggest that or bottom right. I guess potentially we could ONLY have keyboard shortcut plus an action in the top (OS) menu

> Another question I have is will the render view naturally scroll to the place that is undone/redone? I think that might be nice but not sure if that's too much jumping around

I'm hopeful that this won't be too much of an issue since in theory you will likely be undoing recent changes... it doesn't seem super straightforward to know which part of the AST changed unless we push some logic into the components/authorviews

**Comment by mathisonian** [comment]
Alright, I updated this with the basic functionality and all seems to be working as expected. Added keyboard shortcuts per @tanalan's suggestion, currently the buttons are just floated to the bottom right corner, the styles can definitely be improved still but I'm going to merge as a first cut.

**Pull request merged**
